### PR TITLE
Tag blog pages

### LINKED ISSUE #25: Add dedicated tag pages for blog articles
Currently, our blog uses tags but doesn't offer standalone pages for each tag. 

- Create individual pages for each tag, e.g., /blog/categories/:tagName
- Add a dropdown in the navbar under 'blog' listing all tags.
- Allow navigation to the tag page when a tag is selected from the dropdown.

### PR DESCRIPTION
**Pull request by DriftingSands**
Adding blog pages that show blogs filtered by category.
Added blog categories page.

Fix #25 

Test URLs:
- Before: https://main--www--headwire-edge-delivery.hlx.page/blog/categories
- After: https://tag-blog-pages--www--headwire-edge-delivery.hlx.page/blog/categories

- Before: https://main--www--headwire-edge-delivery.hlx.page/blog/categories/seo
- After: https://tag-blog-pages--www--headwire-edge-delivery.hlx.page/blog/categories/seo

### CODE REVIEW

**Comment by icaraps** [comment]
@DriftingSands Wasn't the idea to have the list of blog tags as a dropdown menu in the header like https://www.bamboohr.com/blog/ see categories ?

**Comment by DriftingSands** [comment]
CSS for the body and the footer were also adjusted so if the page does not contain enough content to place the footer at the bottom (like the /blog/category/ page), it will still appear at the bottom

**Comment by reusr1** [comment]
@DriftingSands 

- please check the mobile navigation
- figure out how we want to deal with the nav structure when its open and the visitor starts to scroll the page

**Comment by icaraps** [comment]
> please check the mobile navigation

The dropdown is cut off on mobile

Screenshot 2023-10-02 at 09 35 58

**Comment by icaraps** [comment]
@DriftingSands the blog dropdown is not opening when I click on "Blog" on desktop

**Comment by DriftingSands** [comment]
> @DriftingSands the blog dropdown is not opening when I click on "Blog" on desktop

should be fixed real soon along with some other things, CSS from main broke that.

**Pull request merged**
